#!/bin/bash

##This script is to trim sequencing adapters and low quality regions from the sequence read data with Trimmomatic
##Input Data Pair-end reads (PE): Raw R1 & R2 reads (FASTQ); Adapter sequences to remove (FASTA)
##Output: Trimmed R1 & R2 paired and unpaired reads (FASTQ)

##load program
module load trimmomatic/0.39


##run program for my data
##Remove adapters --> ILLUMINACLIP:adapters.fa:2:35:10
##Remove reads containing N > 10% (N represents the base cannot be determined)-->LEADING:10 TRAILING:10
##Remove read containing low quality (Qscore<=5) base which is over 50% of the total base
##HeadCrop:10 will remove the first 10 bases from the start of the read.
##Sliding window:5:30 every 5 bases the program will evaluate the quality of these bases and remove everything under a quality of 30


java -jar /apps/x86-64/apps/spack_0.19.1/spack/opt/spack/linux-rocky8-zen3/gcc-11.3.0/trimmomatic-0.39-iu723m2xenra563gozbob6ansjnxmnfp/bin/trimmomatic-0.39.jar PE -threads 6 -phred33 /home/aubadc002/killifish/fastqc/W4/W4U1_B_1.fq.gz /home/aubadc002/killifish/fastqc/W4/W4U1_B_2.fq.gz W4U1B1filtered_1paired.fq W4U1B1filtered_1unpaired.fq  W4U1B2filtered_2paired.fq W4U1B2filtered_2unpaired.fq ILLUMINACLIP:adapters.fa:2:35:10 HEADCROP:10 LEADING:10 TRAILING:10 SLIDINGWINDOW:5:30 MINLEN:36
java -jar /apps/x86-64/apps/spack_0.19.1/spack/opt/spack/linux-rocky8-zen3/gcc-11.3.0/trimmomatic-0.39-iu723m2xenra563gozbob6ansjnxmnfp/bin/trimmomatic-0.39.jar PE -threads 6 -phred33 /home/aubadc002/killifish/fastqc/W4/W4U2_B_1.fq.gz /home/aubadc002/killifish/fastqc/W4/W4U2_B_2.fq.gz W4U2B1filtered_1paired.fq W4U2B1filtered_1unpaired.fq  W4U2B2filtered_2paired.fq W4U2B2filtered_2unpaired.fq ILLUMINACLIP:adapters.fa:2:35:10 HEADCROP:10 LEADING:10 TRAILING:10 SLIDINGWINDOW:5:30 MINLEN:36
java -jar /apps/x86-64/apps/spack_0.19.1/spack/opt/spack/linux-rocky8-zen3/gcc-11.3.0/trimmomatic-0.39-iu723m2xenra563gozbob6ansjnxmnfp/bin/trimmomatic-0.39.jar PE -threads 6 -phred33 /home/aubadc002/killifish/fastqc/W4/W4U3_B_1.fq.gz /home/aubadc002/killifish/fastqc/W4/W4U3_B_2.fq.gz W4U3B1filtered_1paired.fq W4U3B1filtered_1unpaired.fq  W4U3B2filtered_2paired.fq W4U3B2filtered_2unpaired.fq ILLUMINACLIP:adapters.fa:2:35:10 HEADCROP:10 LEADING:10 TRAILING:10 SLIDINGWINDOW:5:30 MINLEN:36
java -jar /apps/x86-64/apps/spack_0.19.1/spack/opt/spack/linux-rocky8-zen3/gcc-11.3.0/trimmomatic-0.39-iu723m2xenra563gozbob6ansjnxmnfp/bin/trimmomatic-0.39.jar PE -threads 6 -phred33 /home/aubadc002/killifish/fastqc/W4/W4U4_B_1.fq.gz /home/aubadc002/killifish/fastqc/W4/W4U4_B_2.fq.gz W4U4B1filtered_1paired.fq W4U4B1filtered_1unpaired.fq  W4U4B2filtered_2paired.fq W4U4B2filtered_2unpaired.fq ILLUMINACLIP:adapters.fa:2:35:10 HEADCROP:10 LEADING:10 TRAILING:10 SLIDINGWINDOW:5:30 MINLEN:36


exit
